### ISSUE TITLE
搜索界面中，我的位置 不能及时更新城市

### ISSUE THREAD

**Issue by laolin** [laolin/app-b#3]
从上海，到南京后，点我的位置，结果还是上海。

**Comment by linjianhong** [comment]
我的位置，指的是我所处的位置。是否改为地图中心的位置？这在 /search中已预留了

**Comment by laolin** [comment]
不要地图中心位置。功能就是要我所处的位置

**Comment by laolin** [comment]
代码中原来是一进来就自动获得当前地点的，每次提示允许获得地址，所以后来关掉了。getCurrentPosition

**Comment by laolin** [comment]
可用 mapData.plugins.geocoder.getAddress 函数 反解析地址信息

**Comment by linjianhong** [comment]
优先使用精确定位。已更新到develop分支，更新到test。
