### ISSUE TITLE
管理员推送自己的钢构厂，给项目的管理员。反之也推送。

### ISSUE THREAD

**Issue by laolin** [laolin/app-b#4]
钢构厂的管理员推送自己的钢构厂给项目的管理员。
反之，钢项目的管理员推送自己的项目给钢构厂的管理员。

一天限发给50个人。

超级管理员随便发。
管理多厂的情况。

**Comment by linjianhong** [comment]
界面、接口通了，但还没实际发。可以先test中试用一下

**Comment by laolin** [comment]
接收人点击进来最好能有方法记录跟踪。可结合 #12 号issue 记录功能

**Comment by linjianhong** [comment]
推送功能已完成，其它的如记录跟踪、权限，已有另行Issuse（#12 , #18 , #19）
