### ISSUE TITLE
非https地址

### ISSUE THREAD

**Issue by laolin** [laolin/app-b#44]
这个地址应该没什么用，http://qr.liantu.com/api.php?text={{url}}

Mixed Content: The page at 'https://qinggaoshou.com/cmoss.html#!/stee-feed-add?type=steefac&id=12522' was loaded over HTTPS, but requested an insecure image 'http://qr.liantu.com/api.php?text={{url}}'. This content should also be served over HTTPS.

**Comment by linjianhong** [comment]
已删除
